תשובות לתרגיל חימום והרחבה לגבי GRAD

In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.tensor(4.0, requires_grad =True)
y = 2*(x**3)+2*x+1

NameError: name 'torch' is not defined

In [ ]:
x

tensor(4., requires_grad=True)

יש את  איקס ואת וואי
- מי המשתנה הבלתי תלוי? מי המשתנה הבלתי תלוי?

In [ ]:
#print out the output of y
y

tensor(137., grad_fn=<AddBackward0>)

In [ ]:
# create a derivative to y
y.backward()

In [ ]:
# what is the slope (נגזרת) of y at the point x is at?
x.grad

tensor(98.)

In [ ]:
# look at the printed output, what hapend ? why is the derivative wrong?
#can you fix it?
a = torch.tensor(2.0, requires_grad =True)

for epoch in range(3):

    b = a**2
    b.backward()
    print (f"epoch{epoch+1}- {a.grad}")
    #fix here

epoch1- 4.0
epoch2- 8.0
epoch3- 12.0


In [ ]:
a = torch.tensor(1.0, requires_grad =True)

for epoch in range(3):

    b = a**2
    b.backward()
    print (f"epoch{epoch+1}- {a.grad}")
    a.grad.zero_()

epoch1- 2.0
epoch2- 2.0
epoch3- 2.0


In [ ]:
a = torch.tensor(1.0, requires_grad =True)

for epoch in range(3):
  with torch.no_grad():
      b = a**2

      print (f"epoch{epoch+1}- {a.grad}")


epoch1- None
epoch2- None
epoch3- None


In [ ]:
a = torch.tensor(1.0, requires_grad =True)

for epoch in range(3):
    b = a**2
    b.backward()
    print (f"epoch{epoch+1}- {a.grad}")
    a.grad.zero_()
    with torch.no_grad():
      b = a**2

      print (f"epoch{epoch+1}- {a.grad}")

epoch1- 2.0
epoch1- 0.0
epoch2- 2.0
epoch2- 0.0
epoch3- 2.0
epoch3- 0.0


In [ ]:
for epoch in range(3):
    b = a**2
    b.backward()
    print (f"epoch{epoch+1}- {a.grad}")
    a.grad.zero_()

    b = a**2

    print (f"epoch{epoch+1}- {a.grad}")

epoch1- 2.0
epoch1- 0.0
epoch2- 2.0
epoch2- 0.0
epoch3- 2.0
epoch3- 0.0


## DEVICE

In [ ]:
import torch
import numpy as np

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda:0" if torch.cuda.is_available() else 'cpu'

In [ ]:
device

'cuda:0'

In [ ]:
x_cpu = torch.tensor ([1.0], device = 'cpu')
x_gpu =  torch.tensor ([1.0], device = 'cuda:0')

In [ ]:
x_cpu.device

device(type='cpu')

In [ ]:
x_gpu.device

device(type='cuda', index=0)

In [ ]:
y = x_cpu +x_gpu #error

In [ ]:
t = torch.tensor([1.0])

In [ ]:
t.device

device(type='cpu')

In [ ]:
x_cpu = x_cpu.to(device)

In [ ]:
x_cpu.device

device(type='cuda', index=0)

In [ ]:
y = x_cpu +x_gpu

פוקימון תשובות

In [ ]:
import torch
import numpy as np

In [ ]:
torch.set_printoptions(sci_mode=False)

In [ ]:
#1
attack  = torch.randint (1,11, (12,1))*10
attack

tensor([[ 60],
        [ 60],
        [ 40],
        [ 30],
        [ 10],
        [ 50],
        [100],
        [ 50],
        [ 90],
        [ 30],
        [ 90],
        [ 30]])

In [ ]:
hp=  torch.randint (1,11, (12,1))
hp

tensor([[ 9],
        [ 8],
        [ 9],
        [ 4],
        [ 4],
        [ 3],
        [ 2],
        [10],
        [ 2],
        [ 6],
        [ 2],
        [ 3]])

In [ ]:
speed = torch.rand(12,1)
speed.shape

torch.Size([12, 1])

In [ ]:
defence = torch.randint(10,51, (12,1))
defence

tensor([[38],
        [23],
        [11],
        [39],
        [30],
        [17],
        [34],
        [16],
        [15],
        [37],
        [15],
        [27]])

In [ ]:
torch.stack((attack,hp,speed,defence)).squeeze().T

tensor([[   60.0000,     9.0000,     0.3849,    38.0000],
        [   60.0000,     8.0000,     0.2400,    23.0000],
        [   40.0000,     9.0000,     0.7265,    11.0000],
        [   30.0000,     4.0000,     0.5399,    39.0000],
        [   10.0000,     4.0000,     0.3252,    30.0000],
        [   50.0000,     3.0000,     0.0911,    17.0000],
        [  100.0000,     2.0000,     0.9549,    34.0000],
        [   50.0000,    10.0000,     0.1612,    16.0000],
        [   90.0000,     2.0000,     0.3955,    15.0000],
        [   30.0000,     6.0000,     0.6182,    37.0000],
        [   90.0000,     2.0000,     0.8946,    15.0000],
        [   30.0000,     3.0000,     0.4321,    27.0000]])

In [ ]:
torch.stack((attack,hp,speed,defence)).squeeze()

tensor([[   60.0000,    60.0000,    40.0000,    30.0000,    10.0000,    50.0000,
           100.0000,    50.0000,    90.0000,    30.0000,    90.0000,    30.0000],
        [    9.0000,     8.0000,     9.0000,     4.0000,     4.0000,     3.0000,
             2.0000,    10.0000,     2.0000,     6.0000,     2.0000,     3.0000],
        [    0.3849,     0.2400,     0.7265,     0.5399,     0.3252,     0.0911,
             0.9549,     0.1612,     0.3955,     0.6182,     0.8946,     0.4321],
        [   38.0000,    23.0000,    11.0000,    39.0000,    30.0000,    17.0000,
            34.0000,    16.0000,    15.0000,    37.0000,    15.0000,    27.0000]])

In [ ]:
torch.stack((attack,hp,speed,defence)).shape

torch.Size([4, 12, 1])

In [ ]:
#דרך אחרת לסדר
torch.stack((attack,hp,speed,defence)).reshape(4,12).T

tensor([[   60.0000,     9.0000,     0.3849,    38.0000],
        [   60.0000,     8.0000,     0.2400,    23.0000],
        [   40.0000,     9.0000,     0.7265,    11.0000],
        [   30.0000,     4.0000,     0.5399,    39.0000],
        [   10.0000,     4.0000,     0.3252,    30.0000],
        [   50.0000,     3.0000,     0.0911,    17.0000],
        [  100.0000,     2.0000,     0.9549,    34.0000],
        [   50.0000,    10.0000,     0.1612,    16.0000],
        [   90.0000,     2.0000,     0.3955,    15.0000],
        [   30.0000,     6.0000,     0.6182,    37.0000],
        [   90.0000,     2.0000,     0.8946,    15.0000],
        [   30.0000,     3.0000,     0.4321,    27.0000]])

In [ ]:
# עוד דרך
torch.stack((attack,hp,speed,defence)).squeeze().permute(1,0)

tensor([[   60.0000,     9.0000,     0.3849,    38.0000],
        [   60.0000,     8.0000,     0.2400,    23.0000],
        [   40.0000,     9.0000,     0.7265,    11.0000],
        [   30.0000,     4.0000,     0.5399,    39.0000],
        [   10.0000,     4.0000,     0.3252,    30.0000],
        [   50.0000,     3.0000,     0.0911,    17.0000],
        [  100.0000,     2.0000,     0.9549,    34.0000],
        [   50.0000,    10.0000,     0.1612,    16.0000],
        [   90.0000,     2.0000,     0.3955,    15.0000],
        [   30.0000,     6.0000,     0.6182,    37.0000],
        [   90.0000,     2.0000,     0.8946,    15.0000],
        [   30.0000,     3.0000,     0.4321,    27.0000]])

In [ ]:
pokemon_data = torch.cat((attack,hp,speed,defence),dim =1)

In [ ]:
pokemon_data.shape

torch.Size([12, 4])

In [ ]:
pokemon_data.sum(dim=0)

tensor([640.0000,  62.0000,   5.7640, 302.0000])

In [ ]:
pokemon_data.sum(dim=1)

tensor([107.3849,  91.2400,  60.7265,  73.5399,  44.3252,  70.0911, 136.9549,
         76.1612, 107.3955,  73.6182, 107.8946,  60.4321])

In [ ]:
pokemon_groups = pokemon_data.reshape(4,3,4)

In [ ]:
pokemon_groups

tensor([[[   60.0000,     9.0000,     0.3849,    38.0000],
         [   60.0000,     8.0000,     0.2400,    23.0000],
         [   40.0000,     9.0000,     0.7265,    11.0000]],

        [[   30.0000,     4.0000,     0.5399,    39.0000],
         [   10.0000,     4.0000,     0.3252,    30.0000],
         [   50.0000,     3.0000,     0.0911,    17.0000]],

        [[  100.0000,     2.0000,     0.9549,    34.0000],
         [   50.0000,    10.0000,     0.1612,    16.0000],
         [   90.0000,     2.0000,     0.3955,    15.0000]],

        [[   30.0000,     6.0000,     0.6182,    37.0000],
         [   90.0000,     2.0000,     0.8946,    15.0000],
         [   30.0000,     3.0000,     0.4321,    27.0000]]])

In [ ]:
#new_pokemon_data
new_attack  = torch.randint (1,11, (4,1))*10
new_hp=  torch.randint (1,11, (4,1))
new_speed = torch.rand(4,1)
new_defence = torch.randint(10,51, (4,1))

new_pokemon_data  =torch.stack((new_attack,new_hp, new_speed, new_defence)).squeeze().T

In [ ]:
expended_data= torch.row_stack((pokemon_data, new_pokemon_data))

In [ ]:
#torch.stack((pokemon_data, new_pokemon_data)).reshape(-1,4)

In [ ]:
expended_data.shape

torch.Size([16, 4])

In [ ]:
attack_matrix= torch.rand(4,2) # 4 תכונות לכל פוקימון ושני קרבות לכל אחד מהם

In [ ]:
battle_result = torch.matmul (pokemon_data , attack_matrix)
battle_result

tensor([[ 88.0965,  94.7647],
        [ 74.8665,  79.5142],
        [ 46.5929,  52.1382],
        [ 61.5761,  66.4615],
        [ 35.6438,  40.5840],
        [ 60.1553,  61.3104],
        [120.1873, 120.2663],
        [ 59.8933,  65.7231],
        [ 94.4270,  93.0443],
        [ 60.0198,  66.1318],
        [ 94.5659,  93.4829],
        [ 50.9774,  54.1166]])

In [ ]:
battle_result.min()

tensor(35.6438)

In [ ]:
battle_result.max()-battle_result.min()

tensor(84.6225)

In [ ]:
pokemon_data.mean(dim =0)

tensor([53.3333,  5.1667,  0.4803, 25.1667])

In [ ]:
pokemon_data.mean(dim =1)

tensor([26.8462, 22.8100, 15.1816, 18.3850, 11.0813, 17.5228, 34.2387, 19.0403,
        26.8489, 18.4046, 26.9736, 15.1080])

In [ ]:
grad_tensor = torch.tensor(pokemon_data, requires_grad=True)

<ipython-input-67-035882dd9737>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  grad_tensor = torch.tensor(pokemon_data, requires_grad=True)


In [ ]:
grad_tensor = pokemon_data.clone().detach().requires_grad_(True)

In [ ]:
power_func = ((grad_tensor **2)-100).mean()

In [ ]:
power_func.backward()

In [ ]:
grad_tensor.grad

tensor([[    2.5000,     0.3750,     0.0160,     1.5833],
        [    2.5000,     0.3333,     0.0100,     0.9583],
        [    1.6667,     0.3750,     0.0303,     0.4583],
        [    1.2500,     0.1667,     0.0225,     1.6250],
        [    0.4167,     0.1667,     0.0136,     1.2500],
        [    2.0833,     0.1250,     0.0038,     0.7083],
        [    4.1667,     0.0833,     0.0398,     1.4167],
        [    2.0833,     0.4167,     0.0067,     0.6667],
        [    3.7500,     0.0833,     0.0165,     0.6250],
        [    1.2500,     0.2500,     0.0258,     1.5417],
        [    3.7500,     0.0833,     0.0373,     0.6250],
        [    1.2500,     0.1250,     0.0180,     1.1250]])