<a href="https://colab.research.google.com/github/DanielDekhtyar/AI-Accelerator/blob/main/Module%207%20-%20Machine%20Learning/Basic_TensorFlow_Practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Create a scalar
scalar = tf.constant(5)

# Create a vector
vector = tf.constant([5, 8])

# Create a matrix
matrix = tf.constant([[3, 8, 4, 9], [7, 1, 7, 2], [8, 3, 7, 1]])

# Create a tensor
tensor = tf.constant([[[5, 8, 1], [7, 1, 9]], [[7, 1, 4], [5, 8, 1]]])

# Create a tensor from a Numpy array
np_array = [[[5, 8, 1], [7, 1, 9]], [[7, 1, 4], [5, 8, 1]]]

# Create a rank 2 tensor of ones using TensorFlow
ones = tf.ones([3, 8])

# Create a rank 4 tensor of zeros using TensorFlow
zeros = tf.zeros([6, 9, 1, 4])

 a shop has 3 types of gum
 |cherry|bazocca|extra-sour|           |
 |------|-------|----------|-----------|
 |1.00  |0.50   |0.75      |#prices    |
 | 30   | 20    | 40       |# qnt sold |

 - create a numpy array that reflects the prices and another to reflect the quantety sold
 - convert the arrays to tensorflow tensors
 - create a `sales_per_prod` tensor that has the total amount for each gum type
 - create a tensor `total_sales` that reflects... the total sales. calculate it
 - what are the shape and rank of `total_sales`and of `sales_per_prod`


In [3]:
prices = np.array([1.00, 0.50, 0.75])

In [4]:
prices

array([1.  , 0.5 , 0.75])

In [5]:
qnt_sold = np.array([30, 20, 40])

In [6]:
qnt_sold

array([30, 20, 40])

In [12]:
prices_tensor = tf.constant(prices, dtype='float64')

In [13]:
qnt_sold_tensor = tf.constant(qnt_sold, dtype='float64')

In [14]:
sales_per_prod = prices_tensor * qnt_sold_tensor
sales_per_prod.numpy()

array([30., 10., 30.])