In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
from  sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

In [2]:
df = sns.load_dataset('planets')


In [3]:
df_copy = df.copy()

In [4]:
df.isnull().sum() 

method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [8]:
var = df.isnull().sum()[df.isnull().sum() != 0]#.index

In [9]:
type(var)

pandas.core.series.Series

In [11]:
 df.isnull().sum()[df.isnull().sum() != 0].index

Index(['orbital_period', 'mass', 'distance'], dtype='object')

In [12]:
df.isnull().sum()[df.isnull().sum() != 0].values

array([ 43, 522, 227], dtype=int64)

In [18]:
df.describe().index

Index(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], dtype='object')

In [20]:
df.shape[0]

1035

In [22]:
df.dtypes

method             object
number              int64
orbital_period    float64
mass              float64
distance          float64
year                int64
dtype: object

In [23]:
df.drop('method', axis=1, inplace= True)

In [24]:
#Scaling
scaler = StandardScaler()

In [25]:
scaled_data = (scaler.fit_transform(df)  #v +=1

In [26]:
scaled_data

array([[-0.63328129, -0.06667346,  1.16958442, -0.25478202, -0.77330752],
       [-0.63328129, -0.04338745, -0.11223397, -0.28269391, -0.26961131],
       [-0.63328129, -0.04768618, -0.01000306, -0.33334478,  0.48593301],
       ...,
       [-0.63328129, -0.07690777,         nan, -0.12293417, -0.52145941],
       [-0.63328129, -0.07687187,         nan,  0.03948709, -0.26961131],
       [-0.63328129, -0.07686946,         nan, -0.0055541 , -0.26961131]])

In [27]:
imputer = KNNImputer()

In [28]:
imputed_data = imputer.fit_transform(scaled_data)

In [29]:
imputed_data

array([[-0.63328129, -0.06667346,  1.16958442, -0.25478202, -0.77330752],
       [-0.63328129, -0.04338745, -0.11223397, -0.28269391, -0.26961131],
       [-0.63328129, -0.04768618, -0.01000306, -0.33334478,  0.48593301],
       ...,
       [-0.63328129, -0.07690777,  1.55911042, -0.12293417, -0.52145941],
       [-0.63328129, -0.07687187,  0.50324856,  0.03948709, -0.26961131],
       [-0.63328129, -0.07686946,  0.51478231, -0.0055541 , -0.26961131]])

In [30]:
inversed = scaler.inverse_transform(imputed_data)

In [31]:
inversed

array([[1.0000000e+00, 2.6930000e+02, 7.1000000e+00, 7.7400000e+01,
        2.0060000e+03],
       [1.0000000e+00, 8.7477400e+02, 2.2100000e+00, 5.6950000e+01,
        2.0080000e+03],
       [1.0000000e+00, 7.6300000e+02, 2.6000000e+00, 1.9840000e+01,
        2.0110000e+03],
       ...,
       [1.0000000e+00, 3.1915239e+00, 8.5860000e+00, 1.7400000e+02,
        2.0070000e+03],
       [1.0000000e+00, 4.1250828e+00, 4.5580000e+00, 2.9300000e+02,
        2.0080000e+03],
       [1.0000000e+00, 4.1877570e+00, 4.6020000e+00, 2.6000000e+02,
        2.0080000e+03]])

In [32]:
df = pd.DataFrame(inversed, columns = df.columns)
#df = pd.DataFrame(scaler.inverse_transform(imputed_data), columns = df.columns)

In [36]:
df['orbital_period'].std()

26263.25972011319

In [37]:
df_copy['orbital_period'].std()

26014.72830406252

In [38]:
df['mass'].std()

3.3325837928457402

In [39]:
df_copy['mass'].std()

3.8186166509616046