In [2]:
import numpy as np
import pandas as pd


In [9]:
ar = np.array([1,2,3,1,1,1])

In [10]:
ar

array([1, 2, 3, 1, 1, 1])

In [11]:
type(ar)

numpy.ndarray

In [12]:
ar.ndim

1

In [13]:
ar.shape

(6,)

In [14]:
ar[1]

2

In [15]:
ar[0]

1

In [17]:
#ar[0, 0] # error - ndim

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [20]:
ar2= np.array([[1,2,3],[4,5,6]])

In [54]:
ar2.size

6

In [21]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
len(ar2)

2

In [23]:
ar2.ndim

2

In [24]:
ar2.shape

(2, 3)

In [27]:
ar2[0,0]

1

In [28]:
ar2[0][0]

1

In [30]:
ar2[1][1]

5

In [56]:
ar3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [33]:
ar3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [57]:
len(ar3)

2

In [58]:
ar3.size

12

In [34]:
ar3.ndim

3

In [35]:
ar3.shape

(2, 2, 3)

In [36]:
ar3 = np.array([[[1,2,3],[4,5,6]],
                
                [[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6]]])

In [37]:
ar3.ndim

3

In [38]:
ar3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [39]:
ar3.shape

(4, 2, 3)

In [40]:
ar3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5]]])

C:\Users\AiFTW\.conda\envs\env_2\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [41]:
ar3

array([[list([1, 2, 3]), list([4, 5, 6])],
       [list([1, 2, 3]), list([4, 5, 6])],
       [list([1, 2, 3]), list([4, 5, 6])],
       [list([1, 2, 3]), list([4, 5])]], dtype=object)

In [42]:
ar3.shape

(4, 2)

In [43]:
ar3.ndim

2

In [44]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [45]:
c = a+b

In [46]:
c

array([5, 7, 9])

In [47]:
type(c)

numpy.ndarray

In [48]:
c.ndim

1

In [51]:
c.shape

(3,)

In [52]:
len(a)

3

In [59]:
result  = []
for  i in range(len(a)):
    result.append(a[i]+ b[i])

In [60]:
result

[5, 7, 9]

In [63]:
result  = []
for  i in range(len(a)): result.append(a[i]+ b[i])

In [64]:
result

[5, 7, 9]

In [69]:
np.random.rand(3)

array([0.95860638, 0.22909671, 0.10909441])

In [70]:
big_a = np.random.rand(10**7)
big_b = np.random.rand(10**7)

In [71]:
big_a.size

10000000

In [74]:
%timeit big_c = big_a + big_b

31.8 ms ± 2.99 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [75]:

result  = []
%timeit for  i in range(len(big_a)): result.append(big_a[i]+ big_b[i])

3.53 s ± 107 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [93]:
df = pd.read_csv ('titanic.csv')

In [78]:
df.head()

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500

In [79]:
df['Fare'] >50

0      False
1       True
2      False
3       True
4      False
       ...  
882    False
883    False
884    False
885    False
886    False
Name: Fare, Length: 887, dtype: bool

In [80]:
df['Fare'] <20

0       True
1      False
2       True
3      False
4       True
       ...  
882     True
883    False
884    False
885    False
886     True
Name: Fare, Length: 887, dtype: bool

In [81]:
conditions = [df['Fare'] >50, df['Fare'] <20]
outcomes = ['Expensive', 'Cheep']
np.select (conditions, outcomes)



array(['Cheep', 'Expensive', 'Cheep', 'Expensive', 'Cheep', 'Cheep',
       'Expensive', '0', 'Cheep', '0', 'Cheep', '0', 'Cheep', '0',
       'Cheep', 'Cheep', '0', 'Cheep', 'Cheep', 'Cheep', '0', 'Cheep',
       'Cheep', '0', '0', '0', 'Cheep', 'Expensive', 'Cheep', 'Cheep',
       '0', 'Expensive', 'Cheep', 'Cheep', 'Expensive', 'Expensive',
       'Cheep', 'Cheep', 'Cheep', 'Cheep', 'Cheep', '0', '0', 'Cheep',
       'Cheep', 'Cheep', 'Cheep', '0', 'Cheep', '0', 'Cheep', 'Expensive',
       '0', 'Expensive', '0', 'Cheep', 'Cheep', '0', '0', 'Cheep',
       'Expensive', 'Expensive', '0', '0', 'Cheep', 'Cheep', 'Cheep',
       'Cheep', 'Cheep', 'Cheep', '0', 'Expensive', 'Cheep', 'Expensive',
       'Cheep', 'Cheep', 'Cheep', '0', 'Cheep', 'Cheep', 'Cheep', 'Cheep',
       '0', 'Cheep', 'Cheep', '0', 'Cheep', 'Expensive', 'Cheep', 'Cheep',
       'Cheep', 'Expensive', '0', 'Cheep', 'Cheep', '0', 'Expensive', '0',
       '0', 'Cheep', 'Cheep', 'Expensive', 'Cheep', 'Cheep', 'Cheep',
 

In [85]:
 s1 = pd.Series(np.select (conditions, outcomes))

In [87]:
pd.concat([df,s1])

0   Age     Fare                                               Name  \
0      NaN  22.0   7.2500                             Mr. Owen Harris Braund   
1      NaN  38.0  71.2833  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2      NaN  26.0   7.9250                              Miss. Laina Heikkinen   
3      NaN  35.0  53.1000        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4      NaN  35.0   8.0500                            Mr. William Henry Allen   
..     ...   ...      ...                                                ...   
882  Cheep   NaN      NaN                                                NaN   
883      0   NaN      NaN                                                NaN   
884      0   NaN      NaN                                                NaN   
885      0   NaN      NaN                                                NaN   
886  Cheep   NaN      NaN                                                NaN   

     Parents/Children Aboard  Pclass     Sex  Siblings/Spouses Aboard  \
0                        0.0     3.0    male                      1.0   
1                        0.0     1.0  female                      1.0   
2                        0.0     3.0  female                      0.0   
3                        0.0     1.0  female                      1.0   
4                        0.0     3.0    male                      0.0   
..                       ...     ...     ...                      ...   
882                      NaN     NaN     NaN                      NaN   
883                      NaN     NaN     NaN                      NaN   
884                      NaN     NaN     NaN                      NaN   
885                      NaN     NaN     NaN                      NaN   
886                      NaN     NaN     NaN                      NaN   

     Survived  
0         0.0  
1         1.0  
2         1.0  
3         1.0  
4         0.0  
..        ...  
882       NaN  
883       NaN  
884       NaN  
885       NaN  
886       NaN  

[1774 rows x 9 columns]

In [88]:
conditions = [df['Fare'] >50, df['Fare'] <20]
outcomes = ['Expensive', 'Cheep']
np.select (conditions, outcomes, 'ok')


array(['Cheep', 'Expensive', 'Cheep', 'Expensive', 'Cheep', 'Cheep',
       'Expensive', 'ok', 'Cheep', 'ok', 'Cheep', 'ok', 'Cheep', 'ok',
       'Cheep', 'Cheep', 'ok', 'Cheep', 'Cheep', 'Cheep', 'ok', 'Cheep',
       'Cheep', 'ok', 'ok', 'ok', 'Cheep', 'Expensive', 'Cheep', 'Cheep',
       'ok', 'Expensive', 'Cheep', 'Cheep', 'Expensive', 'Expensive',
       'Cheep', 'Cheep', 'Cheep', 'Cheep', 'Cheep', 'ok', 'ok', 'Cheep',
       'Cheep', 'Cheep', 'Cheep', 'ok', 'Cheep', 'ok', 'Cheep',
       'Expensive', 'ok', 'Expensive', 'ok', 'Cheep', 'Cheep', 'ok', 'ok',
       'Cheep', 'Expensive', 'Expensive', 'ok', 'ok', 'Cheep', 'Cheep',
       'Cheep', 'Cheep', 'Cheep', 'Cheep', 'ok', 'Expensive', 'Cheep',
       'Expensive', 'Cheep', 'Cheep', 'Cheep', 'ok', 'Cheep', 'Cheep',
       'Cheep', 'Cheep', 'ok', 'Cheep', 'Cheep', 'ok', 'Cheep',
       'Expensive', 'Cheep', 'Cheep', 'Cheep', 'Expensive', 'ok', 'Cheep',
       'Cheep', 'ok', 'Expensive', 'ok', 'ok', 'Cheep', 'Cheep',
       'Expen

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Survived                 887 non-null    int64  
 1   Pclass                   887 non-null    int64  
 2   Name                     887 non-null    object 
 3   Sex                      887 non-null    object 
 4   Age                      887 non-null    float64
 5   Siblings/Spouses Aboard  887 non-null    int64  
 6   Parents/Children Aboard  887 non-null    int64  
 7   Fare                     887 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.6+ KB


In [94]:
df1 = df[['Name', 'Sex', 'Fare', 'Age']]

In [95]:
df1

Name     Sex     Fare   Age
0                               Mr. Owen Harris Braund    male   7.2500  22.0
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  71.2833  38.0
2                                Miss. Laina Heikkinen  female   7.9250  26.0
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  female  53.1000  35.0
4                              Mr. William Henry Allen    male   8.0500  35.0
..                                                 ...     ...      ...   ...
882                               Rev. Juozas Montvila    male  13.0000  27.0
883                        Miss. Margaret Edith Graham  female  30.0000  19.0
884                     Miss. Catherine Helen Johnston  female  23.4500   7.0
885                               Mr. Karl Howell Behr    male  30.0000  26.0
886                                 Mr. Patrick Dooley    male   7.7500  32.0

[887 rows x 4 columns]

In [99]:
pd.concat ([df1, pd.Series(np.select (conditions, outcomes, 'ok'))], axis =1).head(10)

Name     Sex     Fare   Age  \
0                             Mr. Owen Harris Braund    male   7.2500  22.0   
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  71.2833  38.0   
2                              Miss. Laina Heikkinen  female   7.9250  26.0   
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  female  53.1000  35.0   
4                            Mr. William Henry Allen    male   8.0500  35.0   
5                                    Mr. James Moran    male   8.4583  27.0   
6                             Mr. Timothy J McCarthy    male  51.8625  54.0   
7                      Master. Gosta Leonard Palsson    male  21.0750   2.0   
8   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson  female  11.1333  27.0   
9                 Mrs. Nicholas (Adele Achem) Nasser  female  30.0708  14.0   

           0  
0      Cheep  
1  Expensive  
2      Cheep  
3  Expensive  
4      Cheep  
5      Cheep  
6  Expensive  
7         ok  
8      Cheep  
9         ok

In [98]:
s1 = pd.Series(np.select (conditions, outcomes, 'ok'))
pd.concat ([df1, s1], axis =1)

SyntaxError: invalid syntax (542191708.py, line 2)

In [100]:
df1['Age'].between(0,15)

0      False
1      False
2      False
3      False
4      False
       ...  
882    False
883    False
884     True
885    False
886    False
Name: Age, Length: 887, dtype: bool

In [101]:
conditions = [df1['Age'].between(0,15),df1['Age'].between(16,30) ]
outcomes = ['child', 'adult']
np.select (conditions, outcomes, 'old')


array(['adult', 'old', 'adult', 'old', 'old', 'adult', 'old', 'child',
       'adult', 'child', 'child', 'old', 'adult', 'old', 'child', 'old',
       'child', 'adult', 'old', 'adult', 'old', 'old', 'child', 'adult',
       'child', 'old', 'adult', 'adult', 'adult', 'adult', 'old', 'old',
       'adult', 'old', 'adult', 'old', 'adult', 'adult', 'adult', 'child',
       'old', 'adult', 'child', 'adult', 'adult', 'adult', 'adult',
       'adult', 'adult', 'child', 'adult', 'old', 'adult', 'old', 'old',
       'adult', 'adult', 'child', 'child', 'adult', 'old', 'old', 'child',
       'old', 'child', 'adult', 'adult', 'adult', 'adult', 'old', 'adult',
       'adult', 'adult', 'old', 'adult', 'adult', 'adult', 'child',
       'adult', 'adult', 'adult', 'old', 'adult', 'adult', 'old', 'adult',
       'adult', 'adult', 'adult', 'adult', 'adult', 'old', 'adult', 'old',
       'adult', 'old', 'adult', 'old', 'old', 'adult', 'adult', 'adult',
       'old', 'old', 'adult', 'adult', 'adult', 'old'

In [102]:
s2 = pd.Series(np.select (conditions, outcomes, 'old'))

In [104]:
pd.concat([df1,s2],axis =1).head(10)

Name     Sex     Fare   Age  \
0                             Mr. Owen Harris Braund    male   7.2500  22.0   
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  71.2833  38.0   
2                              Miss. Laina Heikkinen  female   7.9250  26.0   
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  female  53.1000  35.0   
4                            Mr. William Henry Allen    male   8.0500  35.0   
5                                    Mr. James Moran    male   8.4583  27.0   
6                             Mr. Timothy J McCarthy    male  51.8625  54.0   
7                      Master. Gosta Leonard Palsson    male  21.0750   2.0   
8   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson  female  11.1333  27.0   
9                 Mrs. Nicholas (Adele Achem) Nasser  female  30.0708  14.0   

       0  
0  adult  
1    old  
2  adult  
3    old  
4    old  
5  adult  
6    old  
7  child  
8  adult  
9  child

In [107]:
conditions = [df1['Age'].between(0,15),df1['Age'].between(10,30) ]
outcomes = ['child', 'adult']
np.select (conditions, outcomes, 'old')
s3 = pd.Series(np.select (conditions, outcomes, 'old'))
pd.concat([df1,s3],axis =1).head(10)

Name     Sex     Fare   Age  \
0                             Mr. Owen Harris Braund    male   7.2500  22.0   
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  71.2833  38.0   
2                              Miss. Laina Heikkinen  female   7.9250  26.0   
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  female  53.1000  35.0   
4                            Mr. William Henry Allen    male   8.0500  35.0   
5                                    Mr. James Moran    male   8.4583  27.0   
6                             Mr. Timothy J McCarthy    male  51.8625  54.0   
7                      Master. Gosta Leonard Palsson    male  21.0750   2.0   
8   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson  female  11.1333  27.0   
9                 Mrs. Nicholas (Adele Achem) Nasser  female  30.0708  14.0   

       0  
0  adult  
1    old  
2  adult  
3    old  
4    old  
5  adult  
6    old  
7  child  
8  adult  
9  child

In [108]:
conditions = [df1['Age'].between(0,15),df['Fare'] >50 ]
outcomes = ['Age condition', 'Fare Condition']
np.select (conditions, outcomes, 'No condition')
s4 = pd.Series(np.select (conditions, outcomes, 'No condition'))
pd.concat([df1,s4],axis =1).head(10)

Name     Sex     Fare   Age  \
0                             Mr. Owen Harris Braund    male   7.2500  22.0   
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  71.2833  38.0   
2                              Miss. Laina Heikkinen  female   7.9250  26.0   
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  female  53.1000  35.0   
4                            Mr. William Henry Allen    male   8.0500  35.0   
5                                    Mr. James Moran    male   8.4583  27.0   
6                             Mr. Timothy J McCarthy    male  51.8625  54.0   
7                      Master. Gosta Leonard Palsson    male  21.0750   2.0   
8   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson  female  11.1333  27.0   
9                 Mrs. Nicholas (Adele Achem) Nasser  female  30.0708  14.0   

                0  
0    No condition  
1  Fare Condition  
2    No condition  
3  Fare Condition  
4    No condition  
5    No condition  
6  Fare Condition  
7   Age condition  
8    No condition  
9   Age condition