In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler,StandarScalar, OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv('titanic.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [27]:
#get_dummies
pd.get_dummies(df,columns = ['Sex', 'Embarked'] ).head(1)
pd.get_dummies(df,columns = ['Sex', 'Embarked'] ).info()
#df.drop('Sex_male')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Sex_female   891 non-null    bool   
 11  Sex_male     891 non-null    bool   
 12  Embarked_C   891 non-null    bool   
 13  Embarked_Q   891 non-null    bool   
 14  Embarked_S   891 non-null    bool   
dtypes: bool(5), float64(2), int64(5), object(3)
memory usage: 74.1+ KB


In [9]:
#OneHOtEncoder
#1 model
ohe =OneHotEncoder(sparse_output=False) # שינוי  טיפוס התוצאה

In [25]:
#fit
encoded = ohe.fit_transform(df[['Sex', 'Embarked']])
print(encoded)

[[0. 1. 0. 0. 1. 0.]
 [1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0.]
 ...
 [1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]]


In [14]:
#3 result to df
df_e =pd.DataFrame(encoded,columns =ohe.get_feature_names_out(['Sex','Embarked']) )
df_e.head(1)

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S  Embarked_nan
0         0.0       1.0         0.0         0.0         1.0           0.0

In [19]:
#4 concat both df's
df_new = pd.concat([df,df_e], axis =1)
df_new.head(1)

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  Sex_female  Sex_male  Embarked_C  \
0      0  A/5 21171  7.25   NaN        S         0.0       1.0         0.0   

   Embarked_Q  Embarked_S  Embarked_nan  
0         0.0         1.0           0.0

In [22]:
#5 drop original columns
df_new = df_new.drop(['Sex','Embarked'], axis =1)

In [24]:
df_new.head(1)

PassengerId  Survived  Pclass                     Name   Age  SibSp  Parch  \
0            1         0       3  Braund, Mr. Owen Harris  22.0      1      0   

      Ticket  Fare Cabin  Sex_female  Sex_male  Embarked_C  Embarked_Q  \
0  A/5 21171  7.25   NaN         0.0       1.0         0.0         0.0   

   Embarked_S  Embarked_nan  
0         1.0           0.0

In [28]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   891 non-null    int64  
 1   Survived      891 non-null    int64  
 2   Pclass        891 non-null    int64  
 3   Name          891 non-null    object 
 4   Age           714 non-null    float64
 5   SibSp         891 non-null    int64  
 6   Parch         891 non-null    int64  
 7   Ticket        891 non-null    object 
 8   Fare          891 non-null    float64
 9   Cabin         204 non-null    object 
 10  Sex_female    891 non-null    float64
 11  Sex_male      891 non-null    float64
 12  Embarked_C    891 non-null    float64
 13  Embarked_Q    891 non-null    float64
 14  Embarked_S    891 non-null    float64
 15  Embarked_nan  891 non-null    float64
dtypes: float64(8), int64(5), object(3)
memory usage: 111.5+ KB


In [30]:
#drop first
#get_dummies
df_dummies = pd.get_dummies(df,columns = ['Sex', 'Embarked'], drop_first =True )

In [32]:
df_dummies.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0   
2                             Heikkinen, Miss. Laina  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0   
4                           Allen, Mr. William Henry  35.0      0      0   

             Ticket     Fare Cabin  Sex_male  Embarked_Q  Embarked_S  
0         A/5 21171   7.2500   NaN      True       False        True  
1          PC 17599  71.2833   C85     False       False       False  
2  STON/O2. 3101282   7.9250   NaN     False       False        True  
3            113803  53.1000  C123     False       False        True  
4            373450   8.0500   NaN      True       False        True

In [33]:
#OneHotEncoder
ohe =OneHotEncoder(sparse_output=False,drop ='first')

In [35]:
#fit
encoded = ohe.fit_transform(df[['Sex', 'Embarked']])
df_e =pd.DataFrame(encoded,columns =ohe.get_feature_names_out(['Sex','Embarked']) )
df_new = pd.concat([df,df_e], axis =1)
df_new = df_new.drop(['Sex','Embarked'], axis =1)
df_new

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name   Age  SibSp  Parch  \
0                              Braund, Mr. Owen Harris  22.0      1      0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0   
2                               Heikkinen, Miss. Laina  26.0      0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0   
4                             Allen, Mr. William Henry  35.0      0      0   
..                                                 ...   ...    ...    ...   
886                              Montvila, Rev. Juozas  27.0      0      0   
887                       Graham, Miss. Margaret Edith  19.0      0      0   
888           Johnston, Miss. Catherine Helen "Carrie"   NaN      1      2   
889                              Behr, Mr. Karl Howell  26.0      0      0   
890                                Dooley, Mr. Patrick  32.0      0      0   

               Ticket     Fare Cabin  Sex_male  Embarked_Q  Embarked_S  \
0           A/5 21171   7.2500   NaN       1.0         0.0         1.0   
1            PC 17599  71.2833   C85       0.0         0.0         0.0   
2    STON/O2. 3101282   7.9250   NaN       0.0         0.0         1.0   
3              113803  53.1000  C123       0.0         0.0         1.0   
4              373450   8.0500   NaN       1.0         0.0         1.0   
..                ...      ...   ...       ...         ...         ...   
886            211536  13.0000   NaN       1.0         0.0         1.0   
887            112053  30.0000   B42       0.0         0.0         1.0   
888        W./C. 6607  23.4500   NaN       0.0         0.0         1.0   
889            111369  30.0000  C148       1.0         0.0         0.0   
890            370376   7.7500   NaN       1.0         1.0         0.0   

     Embarked_nan  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0  
..            ...  
886           0.0  
887           0.0  
888           0.0  
889           0.0  
890           0.0  

[891 rows x 14 columns]