
A **scientific laboratory** tracks the usage of three essential measuring instruments: **a voltmeter, an ammeter, and a thermometer**. Each instrument has a fixed cost:

- **Voltmeter**: $50

- **Ammeter** $30

- **Thermometer**: $20  

The lab technicians use different numbers of these instruments each day, and the lab manager wants to calculate the **total cost of instrument usage** for each day over the past **four days**.

The recorded daily usage data looks like this:

| Day | Voltmeter | Ammeter | Thermometer |
|----|----------|--------|------------|
| 1  | 5        | 7      | 10         |
| 2  | 4        | 6      | 8          |
| 3  | 6        | 5      | 9          |
| 4  | 7        | 8      | 10         |

The manager asks you to **calculate the total cost of instruments used per day** using **PyTorch tensor operations**.

### **Question:**
Using the given instrument prices and daily usage data, how can you compute the total cost of instruments used each day using PyTorch?

Write a PyTorch expression that calculates the total cost for each of the four days as a tensor.


In [6]:
import torch
# Define prices of instruments as a tensor- 3 rows 1 column matrix of prices(voltmeter, ammeter, and thermometer)
inst_price = torch.tensor ([[50],[20],[30]])
inst_price.shape

# Define the matrix (4 days x 3 types of instruments) each day will be a row in the matrix (like the table above)
daily_usage  = torch.tensor([
    [5,7,10] , #day 1
    [4,6,8] ,#day 2
    [6,5,9], #day3
    [7,8,10] #day4
])

daily_usage.shape

torch.Size([4, 3])

In [8]:
total1 = torch.matmul(daily_usage,inst_price )

In [9]:
total1.shape

torch.Size([4, 1])

In [10]:
total1

tensor([[690],
        [560],
        [670],
        [810]])

A **coffee shop** tracks the sales of three types of coffee over four days. Each type of coffee has a fixed price:

- **Espresso**: $3     

- **Latte**: $4  

- **Americano**: $2  

The shop owner wants to calculate the **total revenue** generated from coffee sales for each of the past **four days**.

The recorded daily sales data looks like this:

| Day | Espresso | Latte | Americano |
|----|---------|------|----------|
| 1  | 10      | 15   | 25       |
| 2  | 8       | 10   | 12       |
| 3  | 12      | 10   | 18       |
| 4  | 15      | 20   | 25       |

The shop owner asks you to **calculate the total revenue from coffee sales per day** using **PyTorch tensor operations**.

### **Question:**
Using the given coffee prices and daily sales data, how can you compute the total revenue for each day using PyTorch?

Write a PyTorch expression that calculates the total revenue for each of the four days as a tensor.


In [12]:
# Coffee prices (3 types of coffee) as a row matrix of prices (1 matrix row with 3 values)
coffee_p = torch.tensor([3,4,2])
# Daily sales matrix (4 days x 3 types of coffee) each day will be a row in the matrix (like the table above)
daily_sales = torch.tensor([[10,15,25],
                            [8,10,12],
                            [12,10,18],
                            [15,20,25]])

In [13]:
total2 = torch.matmul(daily_sales,coffee_p )

In [14]:
total2

tensor([140,  88, 112, 175])

In [15]:
daily_sales.shape

torch.Size([4, 3])

In [16]:
coffee_p.shape

torch.Size([3])

In [17]:
total2 = torch.matmul(coffee_p, daily_sales )# Error becose of shape

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 4x3)

In [18]:
total2 = torch.matmul(coffee_p, daily_sales.T )

In [19]:
total2

tensor([140,  88, 112, 175])

דוגמאות מהשיעור

In [20]:
total2.sum()

tensor(515)

In [24]:
daily_sales

tensor([[10, 15, 25],
        [ 8, 10, 12],
        [12, 10, 18],
        [15, 20, 25]])

In [23]:
daily_sales.sum()

tensor(180)

In [25]:
daily_sales.sum(dim=1)

tensor([50, 30, 40, 60])

In [26]:
daily_sales.sum(dim=0)

tensor([45, 55, 80])

In [35]:
tsum = torch.tensor ([[[1,1,1],[2,2,2]],[[3,3,3],[4,4, 4]]])
tsum

tensor([[[1, 1, 1],
         [2, 2, 2]],

        [[3, 3, 3],
         [4, 4, 4]]])

In [31]:
tsum.ndim

3

In [32]:
tsum.shape

torch.Size([2, 2, 3])

In [36]:
tsum.sum()

tensor(30)

In [37]:
tsum.sum(dim=0) # 1+3 / 2+4

tensor([[4, 4, 4],
        [6, 6, 6]])

In [41]:
tsum.sum(dim=0).shape

torch.Size([2, 3])

In [38]:
tsum.sum(dim=1) # 1+2/3+4

tensor([[3, 3, 3],
        [7, 7, 7]])

In [39]:
tsum.sum(dim=1).shape

torch.Size([2, 3])

In [40]:
tsum.sum(dim=2) /#1+1+1/ 2+2+2/3+3+3/4+4+4

tensor([[ 3,  6],
        [ 9, 12]])

In [42]:
tsum.sum(dim=2).shape

torch.Size([2, 2])

In [44]:
daily_sales

tensor([[10, 15, 25],
        [ 8, 10, 12],
        [12, 10, 18],
        [15, 20, 25]])

In [45]:
daily_sales.shape

torch.Size([4, 3])

In [46]:
daily_sales.size()

torch.Size([4, 3])

In [47]:
daily_sales.shape[0]

4

In [48]:
daily_sales.shape[1]

3

In [49]:
daily_sales.shape[0]*daily_sales.shape[1]

12

In [50]:
len(daily_sales)

4

In [52]:
daily_sales.numel()

12

In [54]:
daily_sales.max()

tensor(25)

In [56]:
daily_sales.max().item()

25

In [58]:
daily_sales.max().values # :-(

<function Tensor.values>

In [59]:
torch.max(daily_sales)

tensor(25)

In [61]:
daily_sales.max(dim=1)

torch.return_types.max(
values=tensor([25, 12, 18, 25]),
indices=tensor([2, 2, 2, 2]))

In [62]:
daily_sales

tensor([[10, 15, 25],
        [ 8, 10, 12],
        [12, 10, 18],
        [15, 20, 25]])

In [63]:
daily_sales.min()

tensor(8)

In [64]:
daily_sales.mean() #ERROR

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [65]:
daily_sales.to(torch.float32).mean()

tensor(15.)

In [66]:
daily_sales.to(torch.float32).std()

tensor(5.8465)

In [67]:
t1 = torch.rand(3,5)

In [68]:
t1

tensor([[0.9233, 0.6925, 0.8560, 0.9748, 0.7882],
        [0.3314, 0.4174, 0.4567, 0.5252, 0.4993],
        [0.3263, 0.0243, 0.7834, 0.1072, 0.4345]])

In [70]:
t2 = torch.rand(5,600)
result = torch.matmul(t1,t2)

In [87]:
t3 = torch.arange(100,0, -10)
t3

tensor([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [76]:
t0 = torch.zeros(4,3)
t0

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [77]:
t4 = torch.tensor([[torch.arange(1,10,2)],[torch.arange(1,10,2)]]) #error

TypeError: only integer tensors of a single element can be converted to an index

In [79]:
t4 = torch.stack([t3,t3,t3,t3])

In [80]:
t4

tensor([[100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10]])

In [81]:
t4 = torch.stack([t3]*7)

In [82]:
t4

tensor([[100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10]])

In [84]:
t31 =  torch.arange(0,100, 10)

In [85]:
t31

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [88]:
t3

tensor([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [89]:
t4 = torch.stack([t3,t31])

In [90]:
t4

tensor([[100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90]])

In [91]:
t4 = torch.stack([t3,t31], dim=1)
t4

tensor([[100,   0],
        [ 90,  10],
        [ 80,  20],
        [ 70,  30],
        [ 60,  40],
        [ 50,  50],
        [ 40,  60],
        [ 30,  70],
        [ 20,  80],
        [ 10,  90]])

In [93]:
t5 = t3.repeat(3)
t5

tensor([100,  90,  80,  70,  60,  50,  40,  30,  20,  10, 100,  90,  80,  70,
         60,  50,  40,  30,  20,  10, 100,  90,  80,  70,  60,  50,  40,  30,
         20,  10])

In [94]:
t5 = t3.repeat(3,1)
t5

tensor([[100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10]])

In [95]:
t5 = t3.repeat(3,2)
t5

tensor([[100,  90,  80,  70,  60,  50,  40,  30,  20,  10, 100,  90,  80,  70,
          60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10, 100,  90,  80,  70,
          60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10, 100,  90,  80,  70,
          60,  50,  40,  30,  20,  10]])

In [96]:
t5 = t3.repeat(1,3,1)
t5

tensor([[[100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
         [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
         [100,  90,  80,  70,  60,  50,  40,  30,  20,  10]]])

In [99]:
t5 = t3.repeat(2,3,1)
t5

tensor([[[100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
         [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
         [100,  90,  80,  70,  60,  50,  40,  30,  20,  10]],

        [[100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
         [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
         [100,  90,  80,  70,  60,  50,  40,  30,  20,  10]]])

In [100]:
t5 = t3.repeat(1,3,1)
t5

tensor([[[100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
         [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
         [100,  90,  80,  70,  60,  50,  40,  30,  20,  10]]])

In [102]:
t5.shape

torch.Size([1, 3, 10])

In [103]:
t_squeeze = t5.squeeze()
t_squeeze.shape

torch.Size([3, 10])

In [104]:
t5 = t3.repeat(1,1,3,1,1)
t5

tensor([[[[[100,  90,  80,  70,  60,  50,  40,  30,  20,  10]],

          [[100,  90,  80,  70,  60,  50,  40,  30,  20,  10]],

          [[100,  90,  80,  70,  60,  50,  40,  30,  20,  10]]]]])

In [105]:
t5.shape

torch.Size([1, 1, 3, 1, 10])

In [106]:
t_squeeze = t5.squeeze()
t_squeeze.shape

torch.Size([3, 10])

In [107]:
t5 = t3.repeat(1,1,3,1,1)
t5

tensor([[[[[100,  90,  80,  70,  60,  50,  40,  30,  20,  10]],

          [[100,  90,  80,  70,  60,  50,  40,  30,  20,  10]],

          [[100,  90,  80,  70,  60,  50,  40,  30,  20,  10]]]]])

In [108]:
t_squeeze = t5.squeeze(dim=1)
t_squeeze.shape

torch.Size([1, 3, 1, 10])

In [110]:
t5 = t3.repeat(1,1,3,1,1)
t5.shape

torch.Size([1, 1, 3, 1, 10])

In [111]:
t_squeeze = t5.squeeze(dim=2)


In [112]:
t_squeeze.shape

torch.Size([1, 1, 3, 1, 10])

In [113]:
t_squeeze = t5.squeeze()

In [114]:
t_squeeze

tensor([[100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
        [100,  90,  80,  70,  60,  50,  40,  30,  20,  10]])

In [115]:
t_squeeze.shape

torch.Size([3, 10])

In [117]:
t_squeeze.numel()

30

In [118]:
t_squeeze.unsqueeze() #error

TypeError: unsqueeze() missing 1 required positional arguments: "dim"

In [123]:
t_squeeze.shape

torch.Size([3, 10])

In [119]:
t_squeeze.unsqueeze(dim=1)

tensor([[[100,  90,  80,  70,  60,  50,  40,  30,  20,  10]],

        [[100,  90,  80,  70,  60,  50,  40,  30,  20,  10]],

        [[100,  90,  80,  70,  60,  50,  40,  30,  20,  10]]])

In [124]:
t_squeeze.unsqueeze(dim=1).shape

torch.Size([3, 1, 10])

In [120]:
t_squeeze.unsqueeze(dim=0)

tensor([[[100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
         [100,  90,  80,  70,  60,  50,  40,  30,  20,  10],
         [100,  90,  80,  70,  60,  50,  40,  30,  20,  10]]])

In [125]:
t_squeeze.unsqueeze(dim=0).shape

torch.Size([1, 3, 10])

In [121]:
t_squeeze.unsqueeze(dim=2)

tensor([[[100],
         [ 90],
         [ 80],
         [ 70],
         [ 60],
         [ 50],
         [ 40],
         [ 30],
         [ 20],
         [ 10]],

        [[100],
         [ 90],
         [ 80],
         [ 70],
         [ 60],
         [ 50],
         [ 40],
         [ 30],
         [ 20],
         [ 10]],

        [[100],
         [ 90],
         [ 80],
         [ 70],
         [ 60],
         [ 50],
         [ 40],
         [ 30],
         [ 20],
         [ 10]]])

In [126]:
t_squeeze.unsqueeze(dim=2).shape

torch.Size([3, 10, 1])

In [122]:
|t_squeeze.unsqueeze(dim=3) #error

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)