In [2]:
import torch

In [3]:
# 1. יצירת טנסור supplies
supplies = torch.tensor([
    [5, 10, 15],   # קבוצה 1
    [8, 12, 9],    # קבוצה 2
    [4, 8, 12]     # קבוצה 3
])

In [4]:
supplies

tensor([[ 5, 10, 15],
        [ 8, 12,  9],
        [ 4,  8, 12]])

In [5]:
# 2. בדיקת מבנה הטנסור
print("Shape:", supplies.shape)
print("ndim", supplies.ndim)
print("data type:", supplies.dtype)

Shape: torch.Size([3, 3])
ndim 2
data type: torch.int64


In [9]:
# 3. הדפסת כמות הפירות של הקבוצה הראשונה
print("Fruits per group 1:", supplies[0,1].item())

Fruits per group 1: 10


In [10]:
supplies[1][2]

tensor(9)

In [11]:
# 4. עדכון כמות החטיפים של הקבוצה השנייה והדפסת הטנסור לאחר העדכון
supplies[1, 2] = 20
print("Updated supplies tensor:\n", supplies)

Updated supplies tensor:
 tensor([[ 5, 10, 15],
        [ 8, 12, 20],
        [ 4,  8, 12]])


In [12]:
# 5. חישוב כמות הציוד הכוללת לכל הקבוצות יחד
total_supplies = supplies.sum()
print("Now the total supply is", total_supplies.item())

Now the total supply is 94


In [13]:
supplies.shape

torch.Size([3, 3])

In [17]:
# 6. הוספת שני ממדים נוספים לטנסור
expanded_supplies = supplies.unsqueeze(0).unsqueeze(2)
#expanded_supplies = supplies.unsqueeze(0)
#expanded_supplies = supplies.unsqueeze(2)
print("Expanded shape with extra dimensions:", expanded_supplies.shape)

Expanded shape with extra dimensions: torch.Size([1, 3, 1, 3])


In [18]:
# 7. כיווץ של ממד אחד ושמירת הטנסור החדש
new_supplies = expanded_supplies.squeeze(0)
print("Shape after squeezing one dimension:", new_supplies.shape)

Shape after squeezing one dimension: torch.Size([3, 1, 3])


In [20]:
new_supplies.shape

torch.Size([3, 1, 3])

In [22]:
new_supplies[2,0,0]

tensor(4)

In [23]:
# 8. שינוי כמות הבקבוקים של הקבוצה השלישית ל-10
new_supplies[2, 0, 0] = 10
print("New supplies after updating bottles for group 3:\n", new_supplies)

New supplies after updating bottles for group 3:
 tensor([[[ 5, 10, 15]],

        [[ 8, 12, 20]],

        [[10,  8, 12]]])


In [24]:
# 9.  חישוב   הפרש כמות הציוד הכוללת עבור הטנסור החדש לעומת הישן
new_total_supplies = new_supplies.sum()
old_total_supplies = supplies.sum()
print(f"Total supplies for NEW supplies: {new_total_supplies.item()}")
print(f"Total supplies for OLD supplies: {old_total_supplies.item()}")
print (f"Delte is: {new_total_supplies.item()-old_total_supplies.item()}")


Total supplies for NEW supplies: 100
Total supplies for OLD supplies: 100
Delte is: 0


In [25]:
new_supplies.shape

torch.Size([3, 1, 3])

In [36]:
torch.randint(0,10, (13,))

tensor([4, 9, 0, 2, 3, 0, 6, 4, 2, 1, 5, 4, 1])

In [37]:
# 10. יצירת טנסור daily_temperature
daily_temperature = torch.randint(18, 36, (13,))
print("Daily temperature:", daily_temperature)

Daily temperature: tensor([18, 27, 26, 35, 26, 32, 28, 28, 27, 35, 20, 35, 25])


In [38]:
# 11. חישוב ממוצע וסטיית תקן של הטמפרטורות
print(f"Max temperature is: {daily_temperature.max()}")
print(f"Mean temperature: {round(daily_temperature.to(torch.float32).mean().item(),1)}") #can't use item on floaf
print(f"Standard deviation: {daily_temperature.to(torch.float32).std().item()}")

Max temperature is: 35
Mean temperature: 27.8
Standard deviation: 5.367280006408691


In [45]:
# 12. שכפול הטמפרטורות ל-3 ימים
temperature_for_3_days = daily_temperature.repeat(3,1)
print(f"Temperature for 3 days\n{temperature_for_3_days}")

Temperature for 3 days
tensor([[18, 27, 26, 35, 26, 32, 28, 28, 27, 35, 20, 35, 25],
        [18, 27, 26, 35, 26, 32, 28, 28, 27, 35, 20, 35, 25],
        [18, 27, 26, 35, 26, 32, 28, 28, 27, 35, 20, 35, 25]])


In [46]:
# 13. יצירת טנסור צריכת מים
water_consumption = torch.randint(1, 6, (3, 13))
print("Water consumption tensor:\n", water_consumption)

Water consumption tensor:
 tensor([[5, 3, 4, 1, 5, 3, 3, 2, 2, 5, 3, 5, 5],
        [1, 2, 4, 2, 1, 3, 1, 4, 3, 5, 1, 5, 4],
        [1, 5, 3, 1, 5, 5, 4, 5, 4, 1, 3, 2, 1]])


In [47]:
# 14. הכפלת הטמפרטורות בצריכת המים
combined_effect = torch.matmul(water_consumption, daily_temperature)
print("Combined water-temperature effect:\n", combined_effect)

Combined water-temperature effect:
 tensor([1265, 1059, 1106])


In [48]:
 water_consumption

tensor([[5, 3, 4, 1, 5, 3, 3, 2, 2, 5, 3, 5, 5],
        [1, 2, 4, 2, 1, 3, 1, 4, 3, 5, 1, 5, 4],
        [1, 5, 3, 1, 5, 5, 4, 5, 4, 1, 3, 2, 1]])

In [49]:
# 15. חישוב סך כל כמות המים שנצרכה על ידי כל קבוצה
total_water_consumption = water_consumption.sum(dim=1)
print("Total water consumption for each group:", total_water_consumption)

Total water consumption for each group: tensor([46, 36, 40])
