In [1]:
import tensorflow as tf
import numpy as np

In [4]:
# Create a scalar
scalar = tf.constant(3)
scalar.ndim

0

In [6]:

# Create a vector
vector = tf.constant([1,2,3,4,0,5,6,7,8])
tf.rank(vector).numpy()


1

In [8]:
# Create a matrix
matrix = tf.constant([[1,2],[23,4],[2,3],[7,8]])
tf.rank(matrix).numpy()
matrix

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1,  2],
       [23,  4],
       [ 2,  3],
       [ 7,  8]], dtype=int32)>

In [9]:
# Create a tensor
tensor = tf.constant([[[2,1],[0,0]],[[2,1],[0,0]],[[2,1],[0,0]]])

tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[2, 1],
        [0, 0]],

       [[2, 1],
        [0, 0]],

       [[2, 1],
        [0, 0]]], dtype=int32)>

In [11]:

# Create a tensor from a Numpy array

np_array = np.array([9,8,7])
np_tensor = tf.constant(np_array)
type(np_tensor)

tensorflow.python.framework.ops.EagerTensor

In [14]:

# Create a rank 2 tensor of ones using TensorFlow
tf.rank(tf.ones([10,5])).numpy()
tf.ones([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [15]:

# Create a rank 4 tensor of zeros using TensorFlow
tf.zeros([2,3,4,5])

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

 a shop has 3 types of gum
 |cherry|bazocca|extra-sour|           |
 |------|-------|----------|-----------|
 |1.00  |0.50   |0.75      |#prices    |
 | 30   | 20    | 40       |# qnt sold |

 - create a numpy array that reflects the prices and another to reflect the quantety sold
 - convert the arrays to tensorflow tensors
 - create a `sales_per_prod` tensor that has the total amount for each gum type
 - create a tensor `total_sales` that reflects... the total sales. calculate it
 - what are the shape and rank of `total_sales`and of `sales_per_prod`


In [19]:
prices = [1., 0.5, 0.75]
qty = [30.,20.,40.]

In [20]:
price_tensor = tf.constant(prices)
qty_tensor = tf.constant(qty)

In [21]:
price_tensor * qty_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([30., 10., 30.], dtype=float32)>

In [22]:
prices =[[1.],[ 0.5], [0.75]]
qty = [[30.,20.,40.]]
price_tensor = tf.constant(prices)
qty_tensor = tf.constant(qty)

In [24]:
tf.linalg.matmul(qty_tensor, price_tensor).numpy()

array([[70.]], dtype=float32)

In [26]:
(qty_tensor@ price_tensor).numpy()

array([[70.]], dtype=float32)